# Generated by Django 4.2.5 on 2023-09-22 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurants', '0002_remove_restaurant_user_and_more'),
        ('app_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_restaurants.restaurant'),
        ),
    ]
