# Generated by Django 4.2.5 on 2023-09-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reviews', '0002_alter_review_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='comment',
        ),
    ]
