# Generated by Django 4.2.5 on 2023-09-22 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_userprofile_profile_picture_and_more'),
        ('app_reviews', '0003_rename_review_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_user.userprofile'),
        ),
    ]
