# Generated by Django 4.2.5 on 2023-09-24 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_alter_userprofile_this_user'),
        ('app_restaurants', '0002_remove_restaurant_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_owner_user', to='app_user.userprofile'),
        ),
    ]
