# Generated by Django 4.2.4 on 2023-09-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='discription',
            new_name='description',
        ),
    ]
