# Generated by Django 4.2.5 on 2023-09-21 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_food', '0002_rename_discription_food_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_images', models.ImageField(upload_to='food_images/')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_food.food')),
            ],
        ),
    ]
