# Generated by Django 4.2.5 on 2023-09-22 00:28

import app_food.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurants', '0002_remove_restaurant_user_and_more'),
        ('app_food', '0003_foodimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_picture',
            field=models.ImageField(default='/profile_pics/temp_pfp_placeholder_REPLACE_LATER.avif', upload_to=app_food.models.get_food_image_upload_path),
        ),
        migrations.AlterField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_restaurants.restaurant'),
        ),
        migrations.DeleteModel(
            name='FoodImages',
        ),
    ]
