# Generated by Django 4.2.5 on 2023-09-24 04:43

import app_food.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_food', '0005_alter_food_food_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_picture',
            field=models.ImageField(upload_to=app_food.models.get_food_image_upload_path),
        ),
    ]
