# Generated by Django 4.2.5 on 2023-09-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_food', '0006_alter_food_food_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
