# Generated by Django 4.2.5 on 2023-09-24 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_restaurants', '0003_alter_restaurant_restaurant_owner'),
        ('app_food', '0008_remove_food_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food', to='app_restaurants.restaurant'),
        ),
    ]
